src/AppBundle/Entity/DSCourtCase.php
<?php
namespace AppBundle\Entity;


use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\Table(name="court_cases")
 */
class DSCourtCase
{
    /**
     * @var int
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var DSCompanyList
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\DSCompanyList")
     * @ORM\JoinColumn(name="company_list_id", referencedColumnName="id")
     */
    private $companyList;

    /**
     * @var array
     * @ORM\Column(type="json")
     */
    private $data;

    /**
     * @var string
     * @ORM\Column(type="string", name="case_number")
     */
    private $caseNumber;

    /**
     * @var \DateTime
     * @ORM\Column(type="datetime", name="case_date")
     */
    private $caseDate;

    /**
     * @var string
     * @ORM\Column(type="string", name="case_type")
     */
    private $caseType;

    /**
     * @var float
     * @ORM\Column(type="decimal", scale=12, precision=2)
     */
    private $sum;

    /**
     * @var bool
     * @ORM\Column(type="boolean", name="is_active")
     */
    private $isActive;

    /**
     * @var string
     * @ORM\Column(type="string", name="current_instance")
     */
    private $currentInstance;

    /**
     * @var \DateTime
     * @ORM\Column(type="datetime", name="instance_date")
     */
    private $instanceDate;

    /**
     * @var DSCourtCaseSide[]
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\DSCourtCaseSide", mappedBy="courtCase")
     */
    private $sides;

    public function __construct()
    {
        $this->sides = new ArrayCollection();
    }

    /**
     * @return int
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * @return DSCompanyList
     */
    public function getCompanyList(): DSCompanyList
    {
        return $this->companyList;
    }

    /**
     * @param DSCompanyList $companyList
     * @return DSCourtCase
     */
    public function setCompanyList(DSCompanyList $companyList): DSCourtCase
    {
        $this->companyList = $companyList;
        return $this;
    }

    /**
     * @return array
     */
    public function getData(): array
    {
        return $this->data;
    }

    /**
     * @param array $data
     * @return DSCourtCase
     */
    public function setData(array $data): DSCourtCase
    {
        $this->data = $data;
        return $this;
    }

    /**
     * @return string
     */
    public function getCaseNumber(): string
    {
        return $this->caseNumber;
    }

    /**
     * @param string $caseNumber
     * @return DSCourtCase
     */
    public function setCaseNumber(string $caseNumber): DSCourtCase
    {
        $this->caseNumber = $caseNumber;
        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getCaseDate(): \DateTime
    {
        return $this->caseDate;
    }

    /**
     * @param \DateTime $caseDate
     * @return DSCourtCase
     */
    public function setCaseDate(\DateTime $caseDate): DSCourtCase
    {
        $this->caseDate = $caseDate;
        return $this;
    }

    /**
     * @return string
     */
    public function getCaseType(): string
    {
        return $this->caseType;
    }

    /**
     * @param string $caseType
     * @return DSCourtCase
     */
    public function setCaseType(string $caseType): DSCourtCase
    {
        $this->caseType = $caseType;
        return $this;
    }

    /**
     * @return float
     */
    public function getSum(): float
    {
        return $this->sum;
    }

    /**
     * @param float $sum
     * @return DSCourtCase
     */
    public function setSum(float $sum): DSCourtCase
    {
        $this->sum = $sum;
        return $this;
    }

    /**
     * @return bool
     */
    public function isActive(): bool
    {
        return $this->isActive;
    }

    /**
     * @param bool $isActive
     * @return DSCourtCase
     */
    public function setIsActive(bool $isActive): DSCourtCase
    {
        $this->isActive = $isActive;
        return $this;
    }

    /**
     * @return string
     */
    public function getCurrentInstance(): string
    {
        return $this->currentInstance;
    }

    /**
     * @param string $currentInstance
     * @return DSCourtCase
     */
    public function setCurrentInstance(string $currentInstance): DSCourtCase
    {
        $this->currentInstance = $currentInstance;
        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getInstanceDate(): \DateTime
    {
        return $this->instanceDate;
    }

    /**
     * @param \DateTime $instanceDate
     * @return DSCourtCase
     */
    public function setInstanceDate(\DateTime $instanceDate): DSCourtCase
    {
        $this->instanceDate = $instanceDate;
        return $this;
    }

    /**
     * @return DSCourtCaseSide[]|ArrayCollection
     */
    public function getSides()
    {
        return $this->sides;
    }
}

src/AppBundle/Entity/DSCourtCaseSide.php
<?php
namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\Table(name="court_case_sides")
 */
class DSCourtCaseSide
{
    /**
     * @var int
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var DSCourtCase
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\DSCourtCase")
     * @ORM\JoinColumn(name="court_case_id", referencedColumnName="id")
     *
     */
    private $courtCase;

    /**
     * @var array
     * @ORM\Column(type="json")
     */
    private $data;

    /**
     * @var string
     * @ORM\Column(type="string")
     */
    private $name;

    /**
     * @var integer
     * @ORM\Column(type="integer")
     */
    private $type;

    /**
     * @var string
     * @ORM\Column(type="string")
     */
    private $ogrn;

    /**
     * @var string
     * @ORM\Column(type="string")
     */
    private $inn;

    /**
     * @return int
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * @return DSCourtCase
     */
    public function getCourtCase(): DSCourtCase
    {
        return $this->courtCase;
    }

    /**
     * @param DSCourtCase $courtCase
     * @return DSCourtCaseSide
     */
    public function setCourtCase(DSCourtCase $courtCase): DSCourtCaseSide
    {
        $this->courtCase = $courtCase;
        return $this;
    }

    /**
     * @return array
     */
    public function getData(): array
    {
        return $this->data;
    }

    /**
     * @param array $data
     * @return DSCourtCaseSide
     */
    public function setData(array $data): DSCourtCaseSide
    {
        $this->data = $data;
        return $this;
    }

    /**
     * @return string|null
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * @param string $name
     * @return DSCourtCaseSide
     */
    public function setName(string $name): DSCourtCaseSide
    {
        $this->name = $name;
        return $this;
    }

    /**
     * @return int
     */
    public function getType(): ?int
    {
        return $this->type;
    }

    /**
     * @param int|null $type
     * @return DSCourtCaseSide
     */
    public function setType(?int $type): DSCourtCaseSide
    {
        $this->type = $type;
        return $this;
    }

    /**
     * @return string|null
     */
    public function getOgrn(): ?string
    {
        return $this->ogrn;
    }

    /**
     * @param string|null $ogrn
     * @return DSCourtCaseSide
     */
    public function setOgrn(?string $ogrn): DSCourtCaseSide
    {
        $this->ogrn = $ogrn;
        return $this;
    }

    /**
     * @return string|null
     */
    public function getInn(): ?string
    {
        return $this->inn;
    }

    /**
     * @param string|null $inn
     * @return DSCourtCaseSide
     */
    public function setInn(?string $inn): DSCourtCaseSide
    {
        $this->inn = $inn;
        return $this;
    }

    /**
     * @return string
     */
    public function getTypeName(): string
    {
        switch ($this->type) {
            case 0:
                return 'В качестве истца';
                break;
            case 1:
                return 'В качестве ответчика';
                break;
            case 2:
                return 'В качестве иного лица';
                break;
            case 3:
                return 'В качестве третьего лица';
                break;
            case 4:
                return 'В любом качестве';
                break;
            default:
                return 'Не определено';
        }

    }

}

src/AppBundle/Controller/CourtCaseController.php
<?php
namespace AppBundle\Controller;

use AppBundle\Manager\DataSourceManager;
use Doctrine\ORM\EntityManager;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

/**
 * Class CourtCaseController
 * @package AppBundle\Controller
 * @Route("/court-case")
 */
class CourtCaseController extends Controller
{

    /**
     * @param Request $request
     * @param int $id
     * @return array
     * @throws \Doctrine\ORM\TransactionRequiredException
     * @throws \Doctrine\ORM\OptimisticLockException
     * @throws \Doctrine\ORM\ORMInvalidArgumentException
     * @throws \Doctrine\ORM\ORMException
     * @throws \Symfony\Component\HttpKernel\Exception\NotFoundHttpException
     * @throws \LogicException
     * @throws \InvalidArgumentException
     *
     * @Route("/view/{id}", name="court_case_view", requirements={"id" : "\d+"})
     * @Method("GET")
     * @Template()
     */
    public function viewAction(Request $request, int $id): array
    {
        $em = $this->getCurrentLiteEm($request);

        $courtCase = $em->find('AppBundle:DSCourtCase', $id);

        if (null === $courtCase) {
            throw $this->createNotFoundException();
        }

        return ['courtCase' => $courtCase];
    }

    /**
     * @param Request $request
     * @return EntityManager
     * @throws \InvalidArgumentException
     * @throws \Symfony\Component\HttpKernel\Exception\NotFoundHttpException
     * @throws \LogicException
     */
    private function getCurrentLiteEm(Request $request): EntityManager
    {
        $reportManager = $this->get('reports.manager');
        $reportManager->setEm($this->getDoctrine()->getManager('default'));
        $currentDs = $reportManager->getCurrentDS($request);

        if (null === $currentDs) {
            throw $this->createNotFoundException();
        }

        return DataSourceManager::createEntityManagerSQLite(
            $currentDs->getFileDb(), $this->getDoctrine()->getManager('dslite')
        );
    }


}

src/AppBundle/Resources/views/CourtCase/view.html.twig
{% extends '::basedt.html.twig' %}

{% block main %}
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="ibox">
            <div class="ibox-content">

                <div class="row">
                    <div class="col-lg-12">
                        <div class="m-b-md">
                            <a href="#" class="btn btn-white btn-xs pull-right">Редактировать арбитражное дело</a>
                            <h2>Номер дела: {{ courtCase.caseNumber }}</h2>
                        </div>
                        <dl class="dl-horizontal">
                            <dt>Статус</dt>
                            {% if courtCase.active %}
                            <dd><span class="label label-primary">Активное</span></dd>
                            {% else %}
                            <dd><span class="label label-danger">Не активное</span></dd>
                            {% endif %}
                        </dl>
                    </div>
                </div>

                <div class="row">

                    <div class="col-lg-5">
                        <dl class="dl-horizontal">
                            <dt>Компания</dt>
                            <dd>{{ courtCase.companyList.name }}</dd>
                            <dt>ИНН</dt>
                            <dd>{{ courtCase.companyList.inn }}</dd>
                            <dt>Сумма иска</dt>
                            <dd><strong>{{ courtCase.sum|number_format(2, ',', ' ') }} &#8381;</strong></dd>
                            <dt>Тип дела</dt>
                            <dd>{{ courtCase.caseType }}</dd>
                        </dl>
                    </div>

                    <div class="col-lg-7">
                        <dl class="dl-horizontal">
                            <dt>Дата</dt>
                            <dd>{{ courtCase.caseDate is empty ? "Не указана" : courtCase.caseDate|date('d.m.Y') }}</dd>
                            <dt>Текущая инстанция</dt>
                            <dd>{{ courtCase.currentInstance }}</dd>
                            <dt>Последнее событие</dt>
                            <dd>{{ courtCase.instanceDate is empty ? "Не указана" : courtCase.instanceDate|date('d.m.Y') }}</dd>
                        </dl>
                    </div>

                </div>

                <div class="row m-t-sm">
                    <div class="col-lg-12">
                        <div class="panel blank-panel">

                            <div class="panel-heading">
                                <div class="panel-options">
                                    <ul class="nav nav-tabs">
                                        <li class="active">
                                            <a href="#sides" data-toggle="tab" aria-expanded="true">Список участников дела</a>
                                        </li>
                                    </ul>
                                </div>
                            </div>

                            <div class="panel-body">
                                <div class="tab-content">
                                    <div class="tab-pane active" id="sides">
                                        <table class="table table-striped">
                                            <thead>
                                                <tr>
                                                    <th>Наименование</th>
                                                    <th>ИНН</th>
                                                    <th>ОГРН</th>
                                                    <th>Тип участия</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                {% for side in courtCase.sides %}
                                                    <tr>
                                                        <td>{{ side.name }}</td>
                                                        <td>{{ side.inn }}</td>
                                                        <td>{{ side.ogrn }}</td>
                                                        <td>{{ side.typeName }}</td>
                                                    </tr>
                                                {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
{% endblock %}